config/routes.rb
Rails.application.routes.draw do
  resources :personals do
  	collection do
      get :failing
    end
  end
  root 'personals#new'
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  self.table_name =  "contract"
  self.primary_key = "id"

   has_many :inet_services, class_name: 'InetService', foreign_key: 'contractId'
   has_many :contract_parameter_type1, class_name: 'ContractParameterType1', foreign_key: 'cid'
   has_many :contract_parameter_type2, class_name: 'ContractParameterType2', foreign_key: 'cid'
   has_many :contract_parameter_type3, class_name: 'ContractParameterType3', foreign_key: 'cid'
   has_many :contract_parameter_type6, class_name: 'ContractParameterType6', foreign_key: 'cid'
   has_many :phones, class_name: "Phone", foreign_key: "cid"
   has_many :flags, class_name: "Flag", foreign_key: "cid"
end

app/models/contract_parameter_type1.rb
class ContractParameterType1 < ActiveRecord::Base
  self.table_name = "contract_parameter_type_1"
  self.primary_key = "pid"
  
  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/contract_parameter_type2.rb
class ContractParameterType2 < ActiveRecord::Base
  self.table_name = "contract_parameter_type_2"
  self.primary_key = "pid"

  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/contract_parameter_type3.rb
class ContractParameterType3 < ActiveRecord::Base
  self.table_name = "contract_parameter_type_3"
  self.primary_key = "pid"

  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/contract_parameter_type6.rb
class ContractParameterType6 < ActiveRecord::Base
  self.table_name = "contract_parameter_type_6"
  self.primary_key = "pid"

  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/flag.rb
class Flag < ActiveRecord::Base
  self.table_name = "contract_parameter_type_5"
  self.primary_key = "cid"
  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/models/inet_service.rb
class InetService < ActiveRecord::Base
  self.table_name = "inet_serv_14"
  belongs_to :contract, class_name: 'Contract', foreign_key: 'contractId'
end

app/models/personal.rb
class Personal
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Slug

  after_create :personal_completion_notification

  field :contract_id, type: Integer
  field :contract_title, type: String
  field :contract_comment, type: String
  field :fio, type: String
  field :address_post, type: String
  field :address_connection, type: String
  field :telephone, type: Integer
  field :birthday, type: String
  field :passport, type: String
  field :passport_date, type: String
  field :passport_authority, type: String

  slug :contract_id

  VALID_DATE_REGEX = /\A(\d{1,2}).(\d{1,2}).(\d{4})\z/
  VALID_PHONE_REGEX = /\A79\d{9}\z/

  validates :contract_id, :contract_title, :contract_comment, :fio, :address_post, :address_connection, :passport, :passport_authority, presence: true

  validates :birthday, :passport_date,  presence: true, format: { with: VALID_DATE_REGEX }
  validates :telephone, presence: true, format: { with: VALID_PHONE_REGEX }

  private

    def personal_completion_notification
      PersonalMailer.personal_added(self).deliver
    end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  self.table_name = "contract_parameter_type_phone"
  self.primary_key = "cid"

  belongs_to :contract, class_name: 'Contract', foreign_key: 'cid'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  require "net/ssh"
  before_filter :find_contract, only: [:new, :create, :edit, :update]

  PERMITTED_PARAMS = [:contract_id, :contract_title, :contract_comment, :fio, :address_post,
                      :address_connection, :telephone, :birthday, :passport, :passport_date, :passport_authority]

  def index
    @personals = Personal.all
  end

  def new
    @personal = Personal.new
  end

  def create
    @personal = Personal.new(create_params)
    if @personal.save
      Net::SSH.start(ENV["MIKROTIK_HOST"], "admin", password: ENV["MIKROTIK_PASSWORD"]) do |ssh|
        ssh.exec!("/ip firewall address-list remove [find where comment=#{@r}]")
      end
      @contract.flags.where(pid: 72).update_all(val: 0)
      redirect_to @personal
    else
      render :new
    end
  end

  def show
    @personal = Personal.find(params[:id])
  end

  def failing
  end

  def edit
    @personal = Personal.find(params[:id])
  end

  def update
    @personal = Personal.find(update_params)
    if @personal.update(params[:personal])
      redirect_to @personal
    else
      render :edit
    end
  end

  def delete
    @personal = Personal.find(params[:id])
  end

  def destroy
    @personal = Personal.find(params[:id])
    @personal.destroy
    redirect_to @personal
  end

  def create_params
    params.require(:personal).permit(PERMITTED_PARAMS)
  end

  def update_params; create_params end

  def find_contract
    @r = request.headers["X-Real-IP"]
    if @r.nil? or @r.empty?
      redirect_to failing_personals_path
    else
      ip = @r.split('.').collect(&:to_i).pack('C*')
      inet = InetService.find_by(addressFrom: ip)
      if inet.nil?
        redirect_to failing_personals_path
      else
        @contract = Contract.find(inet.contractId)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/views/layouts/_footer.html.haml
.container
  .row
    .col-lg-12
      &copy; ООО Крыминфоком
      = Time.now.year
      г.

app/views/layouts/_header.html.haml
.navbar.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "ООО Крыминфоком", root_path, class: "navbar-brand"
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Главная" , root_path
        %li= link_to "Контакты", "#"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ООО Крыминфоком
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/header'
    %section.inner-bg
      .container
        .row
          .col-lg-12
            %h1 Уважаемый абонент!
            %p 
              Ввиду того, что данные в Вашем договоре усторели, Вам необходимо предоставить ООО Крыминфоком актуальные данные. Для этого, предлагаем Вам заполнить предложенную нами форму. После заполнения формы Ваши данные попадут к нам в систему биллинга, после чего Вы сможете дальше пользоваться услугой Интернет.
            %p
              Если у Вас возникли вопросы, мы можете обратиться за разъяснениями в абонентский отдел ООО Крыминфоком по телефону: +7(978)838-37-23.
    %section.wrapper
      .container
        .row
          .col-lg-12
            = yield
    %footer
      =render 'layouts/footer'

app/views/personals/_form.html.haml
%h1 Форма для заполнения
= simple_form_for(@personal, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  .form-actions
    = f.input :fio, label: 'ФИО', error: 'ФИО должно быть заполнено', hint: "Например: Иванов Иван Иванович", :input_html => { :class => 'form-control' }, required: true
  .form-actions
    = f.input :address_post, label: 'Адрес (почтовый)', error: 'Необходимо заполнить почтовый адрес', hint: "Например: г. Симферополь, ул. Тургенева, 20", required: true
  .form-actions
    = f.input :address_connection, label: 'Адрес (подключения)', error: 'Необходимо заполнить адрес подключения', hint: "Например: г. Симферополь, ул. Киевская, 114",  required: true
  .form-actions
    = f.input :telephone, label: 'Мобильный телефон', error: 'Необходимо указать мобильный телефон', hint: "Например: +79789999999", required: true
  .form-actions
    = f.input :birthday, label: 'Дата рождения', error: 'Необходимо указать дату рождения', hint: "Например: 27.03.1964г.",  required: true
  .form-actions
    = f.input :passport, label: 'Паспорт серия и номер', error: 'Необходимо указать серию и номер паспорта', hint: "Например: 9213 683567", required: true
  .form-actions
    = f.input :passport_date, label: 'Дата выдачи паспорта', error: 'Необходимо указать дату выдачи паспорта', hint: 'Например: 22.06.2014г', required: true
  .form-actions
    = f.input :passport_authority, label: 'Кем выдан паспорт', error: 'Необходимо указать кем выдан паспорт', hint: 'Например: ФМС 900-003', required: true
    = f.input :contract_id, as: :hidden, input_html: { value: @contract.id }
    = f.input :contract_title, as: :hidden, input_html: { value: @contract.title }
    = f.input :contract_comment, as: :hidden, input_html: { value: @contract.comment }
  .form-actions
    = f.button :submit, "Отправить данные"

app/views/personals/edit.html.haml
%h1 Редактируем запись
= render 'form'

app/views/personals/failing.html.haml
%h1 Ой, а Вашего договора у нас нет!

app/views/personals/info.html.haml
%h1 Personals#info

%p
  = @contract.title
%p
  = @contract.comment
%p
  - @contract.contract_parameter_type1.where(pid: 29).map do |fio|
    = fio.val
%p
  - @contract.contract_parameter_type2.where(pid: 5).map do |post_address|
    = post_address.address
%p
  - @contract.contract_parameter_type2.where(pid: 42).map do |conn_address|
    = conn_address.address
%p
  - if @contract.contract_parameter_type3.where(pid: 8).empty?
    Нет данных об электронной почте
  - else
    - @contract.contract_parameter_type3.where(pid: 8).map do |email|
      = email.email
%p
  - if @contract.phones.empty?
    Нет данных о мобильном телефоне
  - else
    - @contract.phones.where(pid: 14).map do |phone|
      +
      = phone.value
%p
  - if @contract.contract_parameter_type6.where(pid: 58).empty?
    Нет данных о дате рождения
  - else
    - @contract.contract_parameter_type6.where(pid: 58).map do |birthday|
      = birthday.val
%p
  - if @contract.contract_parameter_type1.where(pid: 24).empty?
    Нет данных
  - else
    - @contract.contract_parameter_type1.where(pid: 24).map do |passport|
      = passport.val
%p
  = link_to "edit", edit_personal_path(@contract.to_param)

app/views/personals/new.html.haml
= render 'form'

app/views/personals/show.html.haml
.container
  %div
    = @personal.id
  %div
    = @personal.contract_id
  %div
    = @personal.contract_title
  %div
    = @personal.contract_comment
  %div
    = @personal.fio
  %div
    = @personal.address_post
  %div
    = @personal.address_connection
  %div
    = @personal.telephone
  %div
    = @personal.birthday
  %div
    = @personal.passport
  %div
    = @personal.passport_date

  %div
    = @personal.passport_authority